language: cpp
os: linux
compiler: gcc
env: CONFIG=Release

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - ./configure.sh --all --use-system-libs

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            
        packages:
            - libbotan1.10-dev
            - zlib1g-dev
            - g++-4.8
