language: cpp
os: linux
compiler: gcc
env: CONFIG=Release

script: ./configure.sh --all --use-system-libs

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            
        packages:
            - libbotan1.10-dev
            - zlib1g-dev
            - g++-4.8
